FROM umihico/aws-lambda-selenium-python:latest

COPY requirements.txt ./

COPY application ./application

RUN pip install -r requirements.txt

CMD ["application.functions.simulated_data.pruebas.miprueba"]
