Resources:
  S3BucketAppFrontDistribution:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - S3BucketApp
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
          - DomainName: !Select [ 2, !Split [ "/", !GetAtt S3BucketApp.WebsiteURL ] ]
            Id: S3Origin
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ErrorCachingMinTTL: 10
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ErrorCachingMinTTL: 10
            ResponseCode: 200
            ResponsePagePath: /index.html
        # Remove or comment out the Aliases section
        # Aliases:
        #   - '${self:custom.cloudFrontDomainName}'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        # Remove or comment out the ViewerCertificate section
        # ViewerCertificate:
        #   AcmCertificateArn: ${self:custom.cloudFrontAcmCertificateArn}
        #   SslSupportMethod: sni-only

Outputs:
  S3BucketAppFrontDistributionOutput:
    Value:
      'Fn::GetAtt': [S3BucketAppFrontDistribution, DomainName]
