Resources:
  # ====================================================================================================================
  # [DEFINITION] BUCKET APP > Bucket space to deploy frontend app
  # ====================================================================================================================
  S3BucketApp:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.s3BucketAppName}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html


  # ====================================================================================================================
  # [DEFINITION] BUCKET POLICY > Public access [LANDING + CORE + SUSCRIPTOR]
  # ====================================================================================================================
  S3BucketAppPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: S3BucketApp
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: arn:aws:s3:::${self:custom.s3BucketAppName}/*


  # ====================================================================================================================
  # [DEFINITION] BUCKET APP STORAGE > Bucket space to save multimedia files (with CORS)
  # ====================================================================================================================
  S3BucketStorage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.s3BucketStorageName}
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
              - PUT
              - POST
              - DELETE
            MaxAge: 3000
            ExposedHeaders:
              - x-amz-server-side-encryption
              - x-amz-request-id
              - x-amz-id-2
              - ETag
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256


# ======================================================================================================================
# [OUTPUTS] INFORMATION > Log information
# ======================================================================================================================
Outputs:
  S3BucketApplication:
    Description: ARN Bucket application frontend
    Value: !GetAtt S3BucketApp.Arn

  S3BucketApplicationURL:
    Description: URL Domain bucket host
    Value: !GetAtt S3BucketApp.WebsiteURL

  S3BucketApplicationStorage:
    Description: ARN Bucket application storage files
    Value: !GetAtt S3BucketStorage.Arn