Resources:
  PropertiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Properties
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema: 
        - AttributeName: pk
          KeyType: HASH

  ReservationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Reservations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema: 
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE

  chatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Chats
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema: 
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE