# ======================================================================================================================
# [DEFINITION] ENVIRONMENT CONFIGURATIONS
# ======================================================================================================================
# TODO: Revise <stage parameters> from serverless v3 (new release function)
environment:
  production:
    # APP SECURITY
    appSecurity: ${file(serverless_resources/app_security.yml):${self:provider.stage}_security}
    # ENABLE SCHEDULE
    enableSchedule: true

  preproduction:
    # APP SECURITY
    appSecurity: ${file(serverless_resources/app_security.yml):${self:provider.stage}_security}
    # ENABLE SCHEDULE
    enableSchedule: true

  develop:
    # APP SECURITY
    appSecurity: ${file(serverless_resources/app_security.yml):${self:provider.stage}_security}
    # ENABLE SCHEDULE
    enableSchedule: false
