"""empty message

Revision ID: 98292cf66541
Revises: 75472e6a306f
Create Date: 2023-11-06 10:59:01.337807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98292cf66541'
down_revision = '75472e6a306f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
